on:
  release:
    types: [created]

jobs:
  releases-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
            
    steps:
      - uses: actions/checkout@v4.2.2
    
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Build Binary
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --config ../goreleaser.test --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
